debug= false
blacklisted_games = []

[steamgrid_db]
auth_key = "Write your authentication key between these quotes"
enabled = true
prefer_animated = false
banned_images = []
only_download_boilr_images = false

[origin]
enabled = true

[gog]
enabled = true
create_symlinks = true

[epic_games]
enabled = true
create_symlinks = true
safe_launch = []

[uplay]
enabled = true

[legendary]
enabled = true

[itch]
enabled = true
create_symlinks = true

[lutris]
enabled = false
executable = "lutris"
flatpak_image = "net.lutris.Lutris//beta"
flatpak = false

[heroic]
enabled = true
launch_games_through_heroic = true

[amazon]
enabled = true

[steam]
create_collections = false
optimize_for_big_picture = false
stop_steam = false
start_steam = false
